config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories
  resources :resturants do
    resources :reviews
  end
  root 'resturants#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.present? && user.admin?
      can :manage, :all
    else
      can :update, Review do |review|
        review.user == user
      end
      can :destroy,Review do |review|
        review.user == user
      end
      can [:read, :create], Review
      can :read, Resturant
      can :read, Category
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :resturant
  validates :name, presence: true
  scope :sorted, lambda { order("categories.position ASC") }
  scope :newest_first, lambda { order("categories.created_at DESC")}
end

app/models/resturant.rb
class Resturant < ActiveRecord::Base
  has_many :categories
  belongs_to :user
  validates :name, presence: true
  scope :sorted, lambda { order("resturants.position ASC") }
  scope :newest_first, lambda { order("resturants.created_at DESC")}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :resturant
  belongs_to :user
  validates :review, length: { :maximum => 140, :minimum => 0 }
  validates :stars, presence: true
  scope :sorted, lambda { order("resturant_user_review.position ASC") }
  scope :newest_first, lambda { order("resturant_user_review.created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :resturant_user_reviews
  has_many :resturants
  def admin?
    self.is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def update
    if @category.update_attributes(cat_params) 
      flash[:notice] = "Category updates successfully"
      redirect_to category_path(@category)
    else 
      flash.now[:error] = @resturant.errors.full_messages.to_sentence
      render :edit
    end
  end

  def create
    if  @category.save
      flash[:notice] = "Category created successfully"
      redirect_to categories_path
    else 
      render :new
    end
  end

  def destroy
    if @resturant.destroy
      flash[:notice] = "Category destroyed successfully."
      redirect_to(:action => 'index')
    else
      render :delete
    end
  end
  private 
  def cat_params
    params.require(:category).permit(:_name).merge(user_id: current_user.id)
  end
end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController
  load_and_authorize_resource
  def update
    if @resturant.update_attributes(resturant_params)
      flash[:notice] = "Resturant updated successfully."
      redirect_to resturant_path(@resturant)
    else
      flash.now[:error] = @resturant.errors.full_messages.to_sentence
      render :edit
    end
  end

  def create
    if @resturant.save
      flash[:notice] = "Resturant created successfully."
      redirect_to resturants_path
    else
      render('new')
    end
  end
  def destroy
    if @resturant.destroy
      flash[:notice] = "Resturant destroyed successfully."
      redirect_to(:action => 'index')
    else
      render('delete')
    end
  end


  private
  def resturant_params
    params.require(:resturant).permit(:name).merge(user_id: current_user.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource

  def create
    if @review.save
      flash[:notice] = "Review created successfully."
      redirect_to resturant_reviews_path(resturant_id: @review.resturant_id)

    else
      render :new
    end
  end
  def destroy
    if @review.destroy
      flash[:notice] = " Review destroyed successfully."
      redirect_to(:action => "index")
    else
      render :delete
    end
  end
  def update
    if @review.update_attributes(review_params)
      flash[:notice] = "Reviw updated successfully."
      redirect_to(:action => 'show', :id => @review.id)
    else
      render('edit')
    end
  end
  private
  def review_params
    params.require(:review).permit(:review, :stars).merge(user_id: current_user.id, resturant_id: params[:resturant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/helpers/resturants_review_helper.rb
module ResturantsReviewHelper
end

app/views/categories/create.html.haml
%h1 Categories#create
%p Find me in app/views/categories/create.html.erb

app/views/categories/delete.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Delete Category
  = form_for(:category, :url => {:action => 'destroy', :id => @category.id}) do |f|
    %p Are you sure you want to permanently delete this category?
    %p= category.name
    .form-buttons
      = submit_tag("Delete category")

app/views/categories/edit.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
.Cateory.edit
  %h2 Update Category
  = form_for(:category, :url => {:action => 'update', :id => @category.id}) do |f|
    %table{:summary => "Page form fields"}
      %tr
        %th Category ID
        %td= f.text_field(:category_id)
      %tr
        %th Name
        %td= f.text_field(:name)
    .form-buttons
      = submit_tag("Update category")

app/views/categories/index.html.haml
- if !flash[:notice].blank?
  .notice
    = flash[:notice]
%div
  %h2 Categories
  = link_to("Add New Category", {:action => 'new'}, :class => 'action new')
  %table.listing
    %tr.header
      %th Category
      %th Name
    - @categories.each do |category|
      %tr
        %td.actions
          = link_to("Show", {:action => 'show', :id => category.id}, :class => 'action show')
          = link_to("Edit", {:action => 'edit', :id => category.id}, :class => 'action edit')
          = link_to("Delete", {:action => 'destroy', :id => category.id}, :class => 'action delete')

app/views/categories/new.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Create Category
  = form_for(:page, :url => {:action => 'create'}) do |f|
    %table
      %tr
        %th Category ID
        %td= f.text_field(:category_id)
      %tr
        %th Name
        %td= f.text_field(:name)
    .form-buttons
      = submit_tag("Create Category")

app/views/categories/show.html.haml
- if !flash[:notice].blank?
  .notice
    = flash[:notice]
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Show categories
  %table
    %tr
      %th Category ID
      %td= @category.id
    %tr
      %th Name
      %td= @category.name

app/views/categories/update.html.haml
%h1 Categories#update
%p Find me in app/views/categories/update.html.erb

app/views/layouts/_navigation.haml
%nav.navbar.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#navbar3", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "http://disputebills.com"}
        %img{:alt => "Dispute Bills", :src => image_path('good-food-logo')}/
    #navbar3.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li.active
          %a.nav-btn{:href => "#"} Home
        %li
          %a.nav-btn{:href => "#"} About
        %li
          %a.nav-btn{:href => "#"} Contact
        %li
          = link_to "Sign out", destroy_user_session_path, method: :delete

        %li.dropdown
          %a.nav-btn.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Categories
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li.dropdown-header Nav header
            %li
              %a{:href => "#"} Separated link
            %li
              %a{:href => "#"} One more separated link

    / /.nav-collapse
  / /.container-fluid

app/views/layouts/application.haml
!!!
%html
  %head
    %title ResturantReview
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{ class: "#{controller_name}-#{action_name}" }
    = render partial: 'layouts/navigation'
    = yield

app/views/resturants/delete.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Delete Resturant
  = form_for(:resturant, :url => {:action => 'destroy', :id => @resturant.id}) do |f|
    %p Are you sure you want to permanently delete this Resturant?
    %p= @resturant.name
    .form-buttons
      = submit_tag("Delete Resturant")

app/views/resturants/edit.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
.restrant_edit
  %h2 Update Resturant
  = form_for(:resturant, method: 'PUT', :url => {:action => 'update', :id => @resturant.id}) do |f|
    %table{:summary => "Rest form fields"}
      %tr
        %th Resturant ID
        %td
          - f.label(:id )
      %tr
        %th Name
        %td= f.text_field(:name)
    .form-buttons
      = submit_tag("Update Resturant")

app/views/resturants/index.html.haml
%h1.rest_style Resturants list
= link_to("Add New Resturant", {:action => 'new'},:class => "rest_style")
%table.rest_style
  %tr.header
    %th Resturant name
    - @resturants.each do |resturant|
      %tr
        %td= resturant.name
        %td= resturant.id
        %td.actions
          = link_to("Show", {:action => 'show', :id => resturant.id}, :class => 'action show')
          = link_to("Edit", {:action => 'edit', :id => resturant.id}, :class => 'action upd')
          = link_to("Delete", {:action => 'destroy', :id => resturant.id}, :class => 'action delete')
          = link_to("Reviews", resturant_reviews_path(resturant))

app/views/resturants/new.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Create a resturant
  = form_for(@resturant) do |f|
    %table{:summary => "Restrant form fields"}
      %tr
        %th Name
        %td= f.text_field(:name)
    .form-buttons
      = submit_tag("Create Resturant")

app/views/resturants/show.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
.container
  %table.rest_style
    %tr.rest_style
      %th Resturant ID
      %td= @resturant.id
    %tr.rest_style
      %th Name
      %td= @resturant.name

app/views/resturants/update.html.haml
%h1 Resturants#update
%p Find me in app/views/resturants/update.html.erb

app/views/reviews/delete.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Delete Review
  = form_for(:resturant_user_reviews, :url => {:action => 'destroy', :id => @resturant_user_reviews.id}) do |f|
    %p Are you sure you want to permanently delete this review?
    %p= @resturant_user_reviews.review
    .form-buttons
      = submit_tag("Delete Review")

app/views/reviews/edit.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Update Review
  = form_for(:review, :url => {:action => 'update', :id => @review.id}, method: :put) do |f|
    %table{:summary => "Review form fields"}
      %tr
        %th Review
        %td= f.text_field(:review)
      %tr
        %th Stars
        %td= f.text_field(:stars)
    .form-buttons
      = f.submit("Update review")

app/views/reviews/index.html.haml
- if !flash[:notice].blank?
  .notice
    = flash[:notice]
%div
  %h2 Reviews
  = link_to("Add New Review", {:action => 'new'}, :class => 'action new')
  %table.listing
    %tr.header
      %th Review
      %th Stars
    - @reviews.each do |review|
      %tr
        %td= review.user.email
        %td= review.review
        %td= review.stars
        %td
          = link_to("Show", resturant_review_path(resturant_id: review.resturant_id, id: review.id), :class => 'action show')
          = link_to("Edit", edit_resturant_review_path(review.resturant_id, review.id), :class => 'action edit')
          = link_to("Delete", resturant_review_path(review.resturant_id, review.id), method: :delete, :class => 'action delete')

app/views/reviews/new.html.haml
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Create a review
  = form_for([@resturant, @review], :url => {:action => 'create'}) do |f|
    %table
      %tr
        %th Review
        %td= f.text_field(:review)
      %tr
        %th Stars
        %td= f.text_field(:stars)
    .form-buttons
      = f.submit("Add a Review")

app/views/reviews/show.html.haml
- if !flash[:notice].blank?
  .notice
    = flash[:notice]
= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link')
%div
  %h2 Show Reviews
  %table
    %tr
      %th Review ID
      %td= @review.id
    %tr
      %th Name
      %td= @review.user.email
    %tr
      %th Review
      %td= @review.review
    %tr
      %th Stars
      %td= @review.stars
    %tr

app/views/reviews/update.html.haml
%h1 ResturantsReview#update
%p Find me in app/views/resturants_review/update.html.erb